import { ReactElement } from "react";
import Head from "next/head";
import { NextPageWithLayout } from "./_app";
import Header from "@/components/layout/header/header";
import Footer from "@/components/layout/footer/footer";

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello world</h1>
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Header />
      {page}
      <Footer />
    </>
  );
};

export default Home;
