import { ReactElement } from "react";
import Head from "next/head";
import { GetStaticPropsResult } from "next";
import { NextPageWithLayout } from "./_app";
import Header from "@/components/layout/header/header";
import Footer from "@/components/layout/footer/footer";
import PostCard from "@/components/PostCard/postCard";
import { IPost } from "../models/post";
import styles from "./index.module.css";

export interface HomeProps {
  posts: IPost[];
}

const Home: NextPageWithLayout<HomeProps> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Kmin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.posts}>
          {posts.map((post) => {
            return <PostCard key={post._id} post={post} />;
          })}
        </div>
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <>
      <Header />
      {page}
      <Footer />
    </>
  );
};

export default Home;

export const getStaticProps = async (): Promise<
  GetStaticPropsResult<HomeProps>
> => {
  const response = await fetch("http://localhost:3000/api/posts", {
    method: "GET",
  });
  if (response.ok) {
    const posts = await response.json();
    return {
      props: {
        posts: posts.data,
      },
    };
  }
  return {
    props: {
      posts: [],
    },
  };
};
